### ISSUE TITLE
Running SolarUseOptimiser in Docker and Not Receiving Data in ChargeHQ (Growatt)

### ISSUE THREAD

**Issue by ashwin-gupta** [danwale/SolarUseOptimiser#1]
**Describe the bug**
There is no data being outputted to ChargeHQ API despite all Growatt config fields being updated.

**To Reproduce**
Run project in docker using docker compose up -d

**Expected behaviour**
Data should be retrieved from Growatt and fed into ChargeHQ

**Logs/Screenshots**
```
solaruseoptimiser-main-huawei-solar-1  | Reading appsettings.json from: /etc/solaruseoptimiser
solaruseoptimiser-main-huawei-solar-1  | ConfigureServices called
solaruseoptimiser-main-huawei-solar-1  | 2023-04-30 02:20:47.865 +00:00 [INF] Starting Polling. The interval is every 300000ms.
```

**Service Information:**
 - Version 1.0.7

**Additional context**
I am new to docker, but would appreciate some help as I have played around with the code and cant seem to find why it wont retrieve data.

**Comment by danwale** [comment]
Can you change the logging level to Debug and capture the output again by any chance, at the Information level it's seeming like it's not doing the query at all because that should have appeared next even at Information level.

**Comment by ashwin-gupta** [comment]
How can I change the logging level? I tried changing it through Timer = new Timer(DataSource.PollRate * 100); But didnt seem to change anything.

**Comment by ashwin-gupta** [comment]
`2023-04-30 19:31:50 solaruseoptimiser-main-huawei-solar-1  | Reading appsettings.json from: /etc/solaruseoptimiser

2023-04-30 19:31:50 solaruseoptimiser-main-huawei-solar-1  | ConfigureServices called

2023-04-30 19:31:51 solaruseoptimiser-main-huawei-solar-1  | 2023-04-30 19:31:51.086 +10:00 [DBG] Configured Logger

2023-04-30 19:31:52 solaruseoptimiser-main-huawei-solar-1  | 2023-04-30 19:31:52.697 +10:00 [INF] Starting Polling. The interval is every 60000ms.`


Didnt change much other than the interval increasing. Is it possible that I have it setup incorrectly?

**Comment by danwale** [comment]
Oh you don't want to be changing the code at all, just the configuration
settings, I suspect you have incorrect settings as this is working fine for
a number of users already.

Feel free to share some of your configuration (minus the password). Are you
configuring it via environment variables or have you populated an
appsettings.json file and put it in the mapped location...if you aren't
familiar with Docker I would suggest just using the environment variables
in the docker-compose.yml file as volume mounts are another level of
understanding required.

**Comment by ashwin-gupta** [comment]
Hey, so I got a fresh version of the project, here is the docker-compose.yml file config:
`version: "3"

services:
  huawei-solar:
    image: danwale/solaruseoptimiser:latest
    restart: always
    environment:
      - ROUTING__DATASOURCE=Growatt #Huawei or Growatt
      - ROUTING__TARGET=ChargeHQ
      - GROWATT__BASEURI=https://server.growatt.com/
      - GROWATT__USERNAME= **********
      - GROWATT__PASSWORD= **********
      - GROWATT__POLLRATE=5 #in minutes
      - GROWATT__USEBATTERYDATA=false #true or false value, if a battery is present should its data
      - CHARGEHQ__APIKEY= **********
      - SERILOG__MINIMUMLEVEL=Debug
    volumes:
     - solaruseoptimiser-conf:/etc/solaruseoptimiser

volumes:
  solaruseoptimiser-conf:
`

Do I just run the docker compose up -d command to run and it should be fine?

**Comment by danwale** [comment]
That looks good for a configuration, and yes just running that should get
it up and running, it should do a poll immediately and then once every 5
minutes after that.

**Comment by ashwin-gupta** [comment]
`solaruseoptimiser-main-huawei-solar-1  | 2023-04-30 23:02:57.496 +00:00 [ERR] An exception was caught while polling for power data to send to ChargeHQ.
solaruseoptimiser-main-huawei-solar-1  | System.Net.Http.HttpRequestException: An error occurred while sending the request.
solaruseoptimiser-main-huawei-solar-1  |  ---> System.IO.IOException: The response ended prematurely.
solaruseoptimiser-main-huawei-solar-1  |    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
solaruseoptimiser-main-huawei-solar-1  |    --- End of inner exception stack trace ---
solaruseoptimiser-main-huawei-solar-1  |    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
solaruseoptimiser-main-huawei-solar-1  |    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
solaruseoptimiser-main-huawei-solar-1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
solaruseoptimiser-main-huawei-solar-1  |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
solaruseoptimiser-main-huawei-solar-1  |    at SolarUseOptimiser.GrowattProducer.GetCookies(CancellationToken cancellationToken) in /app/GrowattProducer.cs:line 147
solaruseoptimiser-main-huawei-solar-1  |    at SolarUseOptimiser.GrowattProducer.Authenticate(CancellationTokenSource cancellationTokenSource) in /app/GrowattProducer.cs:line 110
solaruseoptimiser-main-huawei-solar-1  |    at SolarUseOptimiser.PeriodicPoller.PollGenerationStatistics_Elapsed(Object sender, ElapsedEventArgs e) in /app/PeriodicPoller.cs:line 134
solaruseoptimiser-main-huawei-solar-1  | 2023-04-30 23:02:57.497 +00:00 [DBG] JSON Request Content: '{"apiKey":"************","error":"An error occurred while polling the Growatt API"}'
solaruseoptimiser-main-huawei-solar-1  | 2023-04-30 23:02:57.715 +00:00 [INF] Successfully sent error data to ChargeHQ Solar Push API.
solaruseoptimiser-main-huawei-solar-1  | 2023-04-30 23:02:57.715 +00:00 [DBG] Sent the error data successfully to ChargeHQ.`

Had some movement on this overnight, but seems to be showing an error in the app as well as logs as shown above.

**Comment by danwale** [comment]
That appears to be a network issue your Docker setup is having, maybe a firewall being applied, it's not getting the response when it makes requests to Growatt for the data it would seem.

**Comment by ashwin-gupta** [comment]
Odd thing is its outputting the error to ChargeHQ. I have tried pinging google.com and that doesnt seem to work either
![image](https://user-images.githubusercontent.com/65590811/235436985-6ec764fa-14d7-41f2-8383-7d4109bbbcfe.png)

**Comment by danwale** [comment]
Can you confirm that DNS is working in your Docker environment? You might
want to look at adding some DNS references such as the publicly available
Google one that is 8.8.8.8.

It is weird that it can get the error out to the ChargeHQ API still, that
kind of leads me to think it's a firewall issue rather than DNS, letting
outbound traffic but blocking incoming traffic. The push of data to the
ChargeHQ API is a HTTP POST which is pretty much one way (it does look for
a response but if the data gets out it gets out), the request for the
Growatt data requires the request and processing of the response but the
error indicates that when reading that response it terminated early which
would mean it couldn't keep that data stream open to get the response.
